export const FACENS_COURSES = [
  'Engenharia Agronômica',
  'Engenharia Civil',
  'Engenharia de Alimentos',
  'Engenharia de Computação',
  'Engenharia de Produção',
  'Engenharia Elétrica',
  'Engenharia Mecânica',
  'Engenharia Mecatrônica',
  'Engenharia Química',
  'Análise e Desenvolvimento de Sistemas (ADS)',
  'Ciência de Dados e Inteligência Artificial',
  'Defesa Cibernética',
  'Gestão de TI',
  'Jogos Digitais',
  'Sistemas de Informação',
  'Arquitetura e Urbanismo',
  'Biomedicina',
  'Enfermagem',
  'Veterinária',
  'Odontologia',
  'Psicologia'
] as const;
